# Generated by Django 3.2.6 on 2021-11-29 20:52

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ingrese el nombre del cliente', max_length=50)),
                ('dom', models.CharField(help_text='Ingrese el domicilio del cliente', max_length=100)),
                ('mail', models.EmailField(help_text='Ingrese el correo del cliente', max_length=254)),
                ('rfc', models.CharField(help_text='12-13 caracteres <a href="https://www.sat.gob.mx/consultas/44083/consulta-tu-informacion-fiscal "> consulta tu RFC</a>', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ingrese el nombre del empleado', max_length=50)),
                ('rfc', models.CharField(help_text='Ingrese el rfc del empleado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_manten', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(help_text='Ingrese las observaciones del mantenimiento')),
                ('tipo_minero', models.CharField(max_length=20, null=True)),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3)),
                ('total', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=16, max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_modelo', models.CharField(help_text='Ingrese la id la marca (p, ej. NVD, AMD,etc.)', max_length=3, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ingrese la marca (p. ej. AMD,Nvidia, etc)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('precio_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='MXN', editable=False, max_length=3)),
                ('precio', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MXN', max_digits=16, max_length=18)),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.CharField(help_text='Ingrese la id tipo de producto (p, ej. TV, PRO)', max_length=3, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ingrese el tipo de producto (p. ej. Tarjeta de video, Procesador etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3)),
                ('total', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=16, max_length=18)),
                ('fecha', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, help_text='ID único generado para este producto particular en toda la tienda', primary_key=True, serialize=False)),
                ('modelo', models.CharField(help_text='Ingrese el modelo del producto (p. ej. Ryzen 3600X, GeForce 1660 Super, etc.)', max_length=120)),
                ('precio_venta_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='MXN', editable=False, max_length=3)),
                ('precio_venta', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MXN', help_text='Ingrese el precio del producto con su tipo de moneda.', max_digits=16, max_length=18)),
                ('cantidad_existente', models.PositiveIntegerField(help_text='Ingrese la cantidad de producto a añadir o modificar.')),
                ('marca', models.ForeignKey(help_text='Seleccione la marca del producto.', on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('tipo', models.ForeignKey(help_text='Seleccione el tipo de producto.', on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3)),
                ('subtotal', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=16, max_length=18)),
                ('id_manten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mantenimiento')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMatenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3)),
                ('subtotal', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=16, max_length=18)),
                ('id_manten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mantenimiento')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado'),
        ),
    ]
