# Generated by Django 3.2.6 on 2022-10-04 00:24

import django.core.validators
from django.db import migrations, models
import djmoney.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='codigoPostal',
            field=models.CharField(blank=True, help_text='Ingrese el codigo postal del cliente', max_length=5, null=True, verbose_name='Codigo Postal del Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='domicilio',
            field=models.CharField(blank=True, help_text='Ingrese el domicilio del cliente', max_length=50, null=True, verbose_name='Domicilio del Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='estado',
            field=models.CharField(blank=True, choices=[("Aguascalientes'", 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de México', 'Ciudad de México'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], default='Jalisco', help_text='Ingrese el estado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombreCliente',
            field=models.CharField(blank=True, help_text='Ingrese el nombre del cliente', max_length=50, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numTelefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Ingrese el número de teléfono del cliente', max_length=14, null=True, region=None, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(help_text='12-13 caracteres <a href="https://www.sat.gob.mx/consultas/44083/consulta-tu-informacion-fiscal"> consulta tu RFC</a>', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_RFC', message='El RFC deberá tener el formato que la Servicio de Administración Tributaria valida', regex='^([A-ZÑ&]{3,4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1]))((-)?([A-Z\\d]{3}))?$')], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(blank=True, help_text='Ingrese la cantidad de productos en existencia/añadir', max_length=6, null=True, verbose_name='Cantidad de Productos en Existencia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Ingrese la descripción del producto', max_length=200, null=True, verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, help_text='Ingrese el modelo del producto', max_length=40, null=True, verbose_name='Modelo del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=djmoney.models.fields.MoneyField(decimal_places=3, default_currency='MXN', help_text='Ingrese el precio del producto', max_digits=6, max_length=9, verbose_name='Precio del Producto'),
        ),
    ]
