# Generated by Django 3.2.6 on 2021-12-06 15:21

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='nom',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nom',
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='Sin marca', help_text='Ingrese el nombre del servicio.', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MXN', help_text='Ingrese el costo del servicio', max_digits=16, max_length=18),
        ),
    ]
