# Generated by Django 3.2.6 on 2021-10-24 02:42

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallematenimiento',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MXN', help_text='Ingrese el precio del producto con su tipo de moneda.', max_digits=16, max_length=18),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MXN', max_digits=16, max_length=18),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
    ]
