# Generated by Django 3.2.6 on 2021-10-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nom',
            field=models.CharField(max_length=120),
        ),
    ]
