# Generated by Django 3.2.6 on 2021-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211206_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rfc',
            new_name='RFC',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dom',
            new_name='domicilio',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nom',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nom',
            new_name='nombre',
        ),
    ]
