# Generated by Django 3.2.6 on 2022-10-27 00:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221019_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboCompra',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        # migrations.RenameField(
        #     model_name='producto',
        #     old_name='precio_currency',
        #     new_name='precioCompra_currency',
        # ),
        # migrations.RemoveField(
        #     model_name='producto',
        #     name='precio',
        # ),
        # migrations.AddField(
        #     model_name='detalleproducto',
        #     name='preciototal',
        #     field=djmoney.models.fields.MoneyField(decimal_places=3, default=Decimal('0'), default_currency='MXN', max_digits=27, max_length=30),
        # ),
        # migrations.AddField(
        #     model_name='detalleproducto',
        #     name='preciototal_currency',
        #     field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='MXN', editable=False, max_length=3),
        # ),
        # migrations.AddField(
        #     model_name='producto',
        #     name='precioCompra',
        #     field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', help_text='Ingrese el precio del producto', max_digits=9, max_length=9, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(999999), django.core.validators.RegexValidator('[0-9]{1,6}([.][0-9]{1,2})?', message='Cantidad de dígitos superada')], verbose_name='Precio del Producto'),
        # ),
        # migrations.AddField(
        #     model_name='producto',
        #     name='precioVenta',
        #     field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', help_text='Ingrese el precio del producto', max_digits=9, max_length=9, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(999999), django.core.validators.RegexValidator('[0-9]{1,6}([.][0-9]{1,2})?', message='Cantidad de dígitos superada')], verbose_name='Precio del Producto'),
        # ),
        # migrations.AddField(
        #     model_name='producto',
        #     name='precioVenta_currency',
        #     field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='MXN', editable=False, max_length=3),
        # ),
        # migrations.AlterField(
        #     model_name='client',
        #     name='dirEmail',
        #     field=models.EmailField(blank=True, help_text='Ingrese la dirección de correo del cliente', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='El correo es inválido.', regex='[a-z0-9]+@[a-z]+\\.[a-z]{2,3}')], verbose_name='Email del Cliente'),
        # ),
        # migrations.AlterField(
        #     model_name='detalleproducto',
        #     name='subtotal',
        #     field=djmoney.models.fields.MoneyField(decimal_places=3, default=Decimal('0'), default_currency='MXN', max_digits=27, max_length=30),
        # ),
        # migrations.AlterField(
        #     model_name='producto',
        #     name='cantidad',
        #     field=models.IntegerField(blank=True, default=0, help_text='Ingrese la cantidad de productos en existencia/añadir', max_length=6, null=True, verbose_name='Cantidad de Productos en Existencia'),
        # ),
        migrations.CreateModel(
            name='DetallesReciboCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway', models.CharField(blank=True, max_length=50, null=True)),
                ('veh', models.CharField(blank=True, max_length=50, null=True)),
                ('destino', models.CharField(blank=True, max_length=50, null=True)),
                ('po', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, max_length=50, null=True)),
                ('cess', models.CharField(blank=True, max_length=50, null=True)),
                ('tcs', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedetailsbillno', to='app.recibocompra')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('perprice', models.IntegerField(default=1)),
                ('totalprice', models.IntegerField(default=1)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasebillno', to='app.recibocompra')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitem', to='app.producto')),
            ],
        ),
    ]
