# Generated by Django 3.2.6 on 2022-10-14 22:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221014_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproducto',
            name='preciototal',
            field=djmoney.models.fields.MoneyField(decimal_places=3, default=Decimal('0'), default_currency='MXN', max_digits=27, max_length=30),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='preciototal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='client',
            name='dirEmail',
            field=models.EmailField(blank=True, help_text='Ingrese la dirección de correo del cliente', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='El correo es inválido.', regex='[a-z0-9]+@[a-z]+\\.[a-z]{2,3}')], verbose_name='Email del Cliente'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='subtotal',
            field=djmoney.models.fields.MoneyField(decimal_places=3, default=Decimal('0'), default_currency='MXN', max_digits=27, max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, help_text='Ingrese la cantidad de productos en existencia/añadir', max_length=6, null=True, verbose_name='Cantidad de Productos en Existencia'),
        ),
    ]
