# Generated by Django 3.2.6 on 2021-11-15 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211023_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('editar_productos', 'Set book as returned'),)},
        ),
    ]
