# Generated by Django 3.2.6 on 2021-12-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_detalleproducto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
