# Generated by Django 3.2.6 on 2022-10-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221012_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleitem', to='app.producto'),
        ),
    ]
