# Generated by Django 3.2.6 on 2022-10-27 03:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221026_1916'),
    ]

    operations = [

        migrations.AddField(
            model_name='recibocompra',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),

    ]
