# Generated by Django 3.2.6 on 2021-12-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211206_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoproducto',
            old_name='nom',
            new_name='nombre',
        ),
    ]
