# Generated by Django 3.2.6 on 2022-10-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221004_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.TextField(blank=True, help_text='Ingrese el modelo del producto', max_length=40, null=True, verbose_name='Modelo del producto'),
        ),
    ]
