# Generated by Django 3.2.6 on 2022-10-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221017_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='email',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='phone',
        ),
        migrations.AddField(
            model_name='salebill',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client'),
        ),
    ]
