# Generated by Django 3.2.6 on 2021-10-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_venta_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
