# Generated by Django 3.2.6 on 2021-10-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_venta_id_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='id_mant',
            new_name='id_manten',
        ),
    ]
