# Generated by Django 3.2.6 on 2021-10-21 13:26

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_id_mant_detalleventa_id_manten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mail',
            field=models.EmailField(help_text='Ingrese el correo del cliente', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(help_text='12-13 caracteres <a href="https://www.sat.gob.mx/consultas/44083/consulta-tu-informacion-fiscal "> consulta tu RFC</a>', max_length=13),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_manten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mantenimiento'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.venta'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='observaciones',
            field=models.TextField(help_text='Ingrese las observaciones del mantenimiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_existente',
            field=models.PositiveIntegerField(help_text='Ingrese la cantidad de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=djmoney.models.fields.MoneyField(decimal_places=2, help_text='Ingrese el precio del producto', max_digits=16, max_length=18),
        ),
    ]
