# Generated by Django 3.2.6 on 2022-10-27 06:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221027_0112'),
    ]

    operations = [

        migrations.AlterField(
            model_name='compras',
            name='preciocompra',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1'), default_currency='MXN', help_text='Ingrese el precio del producto', max_digits=9, max_length=9, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(999999), django.core.validators.RegexValidator('[0-9]{1,6}([.][0-9]{1,2})?', message='Cantidad de dígitos superada')], verbose_name='Precio del Producto'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='precioventa',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1'), default_currency='MXN', help_text='Ingrese el precio del producto', max_digits=9, max_length=9, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(999999), django.core.validators.RegexValidator('[0-9]{1,6}([.][0-9]{1,2})?', message='Cantidad de dígitos superada')], verbose_name='Precio del Producto'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Ingrese la cantidad de productos a comprar'),
        ),

        migrations.AlterField(
            model_name='recibocompra',
            name='notas',
            field=models.TextField(blank=True, help_text='Ingrese algún mensaje de ayuda para un mejor control', null=True),
        ),
    ]
