# Generated by Django 3.2.6 on 2022-10-06 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221005_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del empleado', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre ingresado no es válido, revise sus espacios o sintaxis', regex='^[ÁÉÍÓÚA-Z][a-záéíóú]+(\\s+[ÁÉÍÓÚA-Z]?[a-záéíóú]+)*$')], verbose_name='Nombre del Empleado'),
        ),
    ]
