# Generated by Django 3.2.6 on 2022-10-06 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_empleado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(help_text='12-13 caracteres <a href="https://www.sat.gob.mx/consultas/44083/consulta-tu-informacion-fiscal"> consulta tu RFC</a>', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_RFC', message='El RFC deberá tener el formato que la Servicio de Administración Tributaria valida', regex='^([A-ZÑ&]{3,4}) ?(?:- ?)?(\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])) ?(?:- ?)?([A-Z\\d]{2})([A\\d])$')], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(blank=True, default=0, help_text='Ingrese la cantidad de productos en existencia/añadir', max_length=6, null=True, verbose_name='Cantidad de Productos en Existencia'),
        ),
    ]
