# Generated by Django 3.2.6 on 2022-11-07 12:04

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20221106_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='MXN', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=9, max_length=9)),
                ('transaccion_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('MXN', 'MXN $'), ('USD', 'USD $')], default='MXN', editable=False, max_length=3)),
                ('transaccion', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=9, max_length=9)),
                ('fecha_transaccion', models.DateTimeField()),
            ],
        ),
    ]
